### ISSUE TITLE
Chapter 6: Conic Optimization

### ISSUE THREAD

**Issue by glebbelov** [fdabrandao/MO-book-with-AMPL#1]
Use Ipopt, Mosek, Gurobi, Knitro to solve SOCP and exponential cones (Gurobi only SOCP). Progress status for text only:

- [x] Economic order quantity
- [x] The Kelly Criterion
- [x] Markowitz portfolio optimization problem revisited: Mosek fails
- [x] Optimal design of multi-layered building insulation
- [x] Training Support Vector Machines with Conic Programming
- [x] Extra material: Luenberger’s Investment Wheel
- [x] Extra material: Optimal Growth Portfolio

Progress status for models:

- [x] Economic order quantity
- [x] The Kelly Criterion
- [x] Markowitz portfolio optimization problem revisited: Mosek fails
- [x] Optimal design of multi-layered building insulation
- [x] Training Support Vector Machines with Conic Programming
- [x] Extra material: Luenberger’s Investment Wheel
- [x] Extra material: Optimal Growth Portfolio

**Comment by glebbelov** [comment]
Started Economic order quantity [4629c8b](https://github.com/fdabrandao/MO-book-with-AMPL/commit/4629c8be3dee0cc44c57f36e6df130328ee15140)

**Comment by glebbelov** [comment]
@fdabrandao do we need the g parameter for tools.ampl_notebook? It is not self-explanatory and it fails for me:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[196], line 4
      2 import numpy as np
      3 import pandas as pd
----> 4 ampl = tools.ampl_notebook(
      5     modules=["ipopt", "mosek"], # modules to install
      6     license_uuid="default", # license to use
      7     g=globals()      ### --------- Fails for me. Can this be default, would anyone change it?
      8 ) # instantiate AMPL object and register magics

TypeError: ampl_notebook() got an unexpected keyword argument 'g'
```

**Comment by fdabrandao** [comment]
Hi @glebbelov,

You seem to have an outdated version of amplpy. Could you please run `pyton -m install amplpy --upgrade` and try again?

That last argument is necessary to give access to the globals in the notebook and enabling `%%ampl_eval` to access the global object named `ampl`. It cannot be a default because `globals()` returns the global variables accessible from where it is invoked, `globals()` inside a module returns the globals inside that module.

**Comment by fdabrandao** [comment]
ChatGPT told me that `IPython.get_ipython().user_global_ns` gives me access to the global environment of the notebook too so that argument is going to go away in the next release.

**Comment by glebbelov** [comment]
@fdabrandao Concerning the Markowitz, the original notebook presents x' * Sigma * x <= s in the mathematical model, but then <= s^2 in Python. Changing model to <= s allows Mosek to be used. I am doing this in our notebook. Probably, authors should be notified about this mistake. Should I still add a model where the factorized matrix is used?

**Comment by glebbelov** [comment]
@fdabrandao SVM notebook did not run. I fixed general Python code. Should the authors be notified?

**Comment by fdabrandao** [comment]
@glebbelov, for any errors you find in the original notebooks you can open issues at: https://github.com/mobook/MO-book/issues (they asked me to open issues there for any mistakes we find)
