### ISSUE TITLE
Chapter 2 LAD model broke

### ISSUE THREAD

**Issue by marcos-dv** [fdabrandao/MO-book-with-AMPL#6]
I am not able to run [LAD-regression](https://mo-book.ampl.com/notebooks/02/lad-regression.html) (chapter 2), it seems that something broke with some amplpy or numpy update.
The model is very simple:
```
# indexing sets
set I;
set J;

# parameters
param y{I};
param X{I, J};

# variables
var ep{I} >= 0;
var em{I} >= 0;
var m{J} >= 0;
var b;

# constraints
s.t. residuals {i in I}:
    ep[i] - em[i] == y[i] - sum{j in J}(X[i, j] * m[j]) - b;

# objective
minimize sum_of_abs_errors: sum{i in I}(ep[i] + em[i]);
```

To call the model
```
def lad_regression(X, y):
    ampl = AMPL()
    ampl.read("lad_regression.mod")

    n, k = X.shape

    # note use of Python style zero based indexing
    ampl.set["I"] = list(range(n))
    ampl.set["J"] = list(range(k))

    ampl.param["y"] = y
    ampl.param["X"] = X

    ampl.option["solver"] = SOLVER
    ampl.solve()

    return ampl


m = lad_regression(X, y)
m.display("m")
m.display("b")
```

The issue shows up when X is assigned to ampl.param["X"], X is a npdarray and comes from:

`X, y = make_regression(n_samples=n_samples, n_features=n_features, noise=noise)`

**Comment by fdabrandao** [comment]
Thanks for reporting this issue! There was a bug induction in amplpy v0.11.0 that broke the way numpy data could be loaded. It has been fixed in v0.12.1 that has just been released.
